# Generated by Django 4.0.6 on 2022-07-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.CharField(db_index=True, max_length=200)),
                ('technology', models.CharField(db_index=True, max_length=200)),
                ('date_start', models.DateField()),
                ('completed', models.CharField(choices=[('Complete', 'Complete'), ('In progress', 'In progress')], max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
