# Generated by Django 4.0.6 on 2022-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programming_languages',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Javascript', 'Javascript')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Django', 'Django'), ('PyQT', 'PyQT'), ('Scrapy', 'Scrapy'), ('Selenium', 'Selenium')], db_index=True, max_length=200),
        ),
    ]
