# Generated by Django 4.0.6 on 2022-09-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_project_programming_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
