# Generated by Django 4.0.6 on 2022-09-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(default='', max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.CharField(default='', max_length=300, null=True, unique=True),
        ),
    ]
