# Generated by Django 4.0.6 on 2022-09-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0007_project_github_url_project_live_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
