# Generated by Django 4.0.6 on 2022-10-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0008_alter_project_github_url_alter_project_live_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/media/img/'),
        ),
    ]
