# Generated by Django 4.0.6 on 2022-10-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0010_technology_remove_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='programming_languages',
            field=models.CharField(choices=[('None', 'None'), ('Python', 'Python'), ('C++', 'C++'), ('Javascript', 'Javascript')], default='', max_length=200, null=True),
        ),
    ]
