# Generated by Django 4.0.6 on 2022-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0012_alter_project_live_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
