# Generated by Django 4.0.6 on 2022-10-12 01:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0013_alter_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=10),
        ),
    ]
