# Generated by Django 4.0.6 on 2022-11-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0020_remove_project_programming_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default='2022', null=True),
        ),
    ]
