# Generated by Django 4.0.6 on 2022-12-22 03:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0021_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='libraries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
    ]
